### PR TITLE
Add ESLint to codebase

### LINKED ISSUE #7: Add Linting
We should lint the codebase to provide a common code style.

### PR DESCRIPTION
**Pull request by naomi-lgbt**
I've added ESLint to the code and configured the rules based on what I saw in the code style already. The rules ESLint will follow are:

* 2 spaces for indentation
* LF linebreaks
* Doublequotes for strings 
* Semi colons at EOL
* Use `const` over `let` when variables aren't reassigned
* Use `===` not `==`

I've also added a GitHub action that will run the linter against PRs to ensure that codebase changes match the style.

### CODE REVIEW

**Review by Fubinator — APPROVED** [review]
This looks really good! Thank you very much! I'm not that familiar with github actions. Should this just work as soon as I merge your PR?

**Comment by naomi-lgbt** [comment]
It should, yes. Once it's merged I can open a dummy PR to verify the action runs - if it doesn't run, I'll tweak it. 😁

**Comment by Fubinator** [comment]
Sounds good! Do you want me to merge this now or should I wait until tomorrow so you can get the points for the Hacktoberfest?

**Comment by naomi-lgbt** [comment]
It actually counts already, so this is good to merge 😁

**Comment by Fubinator** [comment]
Ah good to know!

**Comment by Fubinator** [comment]
The action works as well, thank you very much!

**Comment by naomi-lgbt** [comment]
Glad I could help!

**Pull request merged**
