### PR TITLE
Added ascii art

### LINKED ISSUE #47: ASCII Art when starting the bot
Let's have some fun: When starting the bot, let's display something with ASCII Art in the console. "Planning Poker Discord Bot" may be a little bit too long for this, so we should either display "PPDB" or "Planning Poker Bot" or something else.

There might be a library for this, I don't really know. If you do not want to use a library for this you can just use this generator: http://patorjk.com/software/taag/#p=display&f=Graffiti&t=Type%20Something%20

### PR DESCRIPTION
**Pull request by ryzbaka**
Planning poker bot displays ascii art on start.
image

### CODE REVIEW

**Comment by ryzbaka** [comment]
The print welcome message test is failing because it has been changed to show the ascii art.

**Comment by Fubinator** [comment]
Hey @ryzbaka what I meant in the issue was to log it into the console. Not send a message to the discord channel.

**Comment by ryzbaka** [comment]
Alright, I'll make the necessary changes.

**Comment by ryzbaka** [comment]
Done
image

**Comment by ryzbaka** [comment]
The ASCII art only shows up in the console now.

**Comment by ryzbaka** [comment]
@Fubinator , kindly review the changes.

**Comment by Fubinator** [comment]
LGTM!

**Pull request merged**
