### PR TITLE
Fix Issue #45

### LINKED ISSUE #45: Send several consecutive messages at once
It is often the case that the bot sends several messages directly after each other. This sometimes leads to delays. All messages that are related should be combined into one message and sent as a whole.

### PR DESCRIPTION
**Pull request by xxKeefer**
Messages in the commands that it is relevant collect all results in to arrays and then join them before sending the message.

this reduces the amount of messages the bot has to send.

### CODE REVIEW

**Comment by xxKeefer** [comment]
i am sorry, i didn't see the tests had been added since my last fetch. i'l fix it so it passes the tests

**Comment by xxKeefer** [comment]
@Fubinator i'm reading these tests, i don't know very much about mockups in jest but it looks like the tests are looking for the bot to send multiple messages. which is exactly what i'm trying to change. Who was the person that wrote the tests so i can get some guidance.

**Comment by Fubinator** [comment]
It was @leonardxfce with PR #38. 

One thing you could try is logging in the tests. It may be enough for now to change the `.toBe()` to `.toMatch()` in all test cases.
ref: https://jestjs.io/docs/en/expect#tomatchregexporstring

**Comment by xxKeefer** [comment]
okidoki, i just didn't want to change the tests to pass the code without permission, seems like a bad habit haha. thanks so much i'll get on it

**Comment by Fubinator** [comment]
@xxKeefer My opinion about changing test cases is that sometimes you can't get around it. But you should change test cases carefully and only if you are aware of your changes. So it is okay to adjust the test cases in this case.

**Comment by xxKeefer** [comment]
I tried my best with the tests, I test to match for the critical components of the messages that i have aggregated.

**Review by Fubinator — APPROVED** [review]

**Pull request merged**
